---
title: "Data_Wrangling_2"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)
library(httr)
```

### NSDUH Data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

```

```{r}
drug_use_html %>%
  html_table() %>%
  first() %>%
  slice(-1) %>% view
```


### Star Wars

```{r}
sw_html = read_html("https://www.imdb.com/list/ls070150896/")

sw_title = 
  sw_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  sw_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

swm_df =
  tibble(
    title = sw_title,
    rev = gross_rev_vec
  )
```


#### Napoleon Dynamite

Reviews

```{r}
dynamite_url = url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(dynamite_url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

### NYC Water Data API

CSV

```{r}
water_df =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content()
```

JSON

```{r}
water_df =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

BRFSS Data

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>%
  content()
```

### Pokemon API

```{r}
poke_data = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```


